# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mcmc_subgraph_internal <- function(df_edges, args) {
    .Call('_mcmcRanking_mcmc_subgraph_internal', PACKAGE = 'mcmcRanking', df_edges, args)
}

mcmc_sample_internal <- function(df_edges, df_nodes, args, start_module) {
    .Call('_mcmcRanking_mcmc_sample_internal', PACKAGE = 'mcmcRanking', df_edges, df_nodes, args, start_module)
}

mcmc_rank_q_internal <- function(df_edges, df_nodes) {
    .Call('_mcmcRanking_mcmc_rank_q_internal', PACKAGE = 'mcmcRanking', df_edges, df_nodes)
}

mcmc_onelong_internal <- function(df_edges, df_nodes, args) {
    .Call('_mcmcRanking_mcmc_onelong_internal', PACKAGE = 'mcmcRanking', df_edges, df_nodes, args)
}

mcmc_onelong_frequency_internal <- function(df_edges, df_nodes, args) {
    .Call('_mcmcRanking_mcmc_onelong_frequency_internal', PACKAGE = 'mcmcRanking', df_edges, df_nodes, args)
}

real_prob_internal <- function(df_edges, df_nodes) {
    .Call('_mcmcRanking_real_prob_internal', PACKAGE = 'mcmcRanking', df_edges, df_nodes)
}

#' Accurate sum of numbers
#'
#' Sums every time only two smallest numbers.
#' This allows calculate the sum of numbers accurate enough.
#' @export
accurate_sum <- function(v) {
    .Call('_mcmcRanking_accurate_sum', PACKAGE = 'mcmcRanking', v)
}

