# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_subgraph_internal <- function(edgelist, gorder, module_size, niter) {
    .Call('_mcmcRanking_sample_subgraph_internal', PACKAGE = 'mcmcRanking', edgelist, gorder, module_size, niter)
}

sample_llh_internal <- function(edgelist, likelihood, niter, fixed_size, start_module) {
    .Call('_mcmcRanking_sample_llh_internal', PACKAGE = 'mcmcRanking', edgelist, likelihood, niter, fixed_size, start_module)
}

mcmc_sample_internal <- function(edgelist, likelihood, fixed_size, niter, start_module) {
    .Call('_mcmcRanking_mcmc_sample_internal', PACKAGE = 'mcmcRanking', edgelist, likelihood, fixed_size, niter, start_module)
}

mcmc_onelong_internal <- function(edgelist, likelihood, module_size, start, end) {
    .Call('_mcmcRanking_mcmc_onelong_internal', PACKAGE = 'mcmcRanking', edgelist, likelihood, module_size, start, end)
}

mcmc_onelong_frequency_internal <- function(edgelist, likelihood, module_size, start, end) {
    .Call('_mcmcRanking_mcmc_onelong_frequency_internal', PACKAGE = 'mcmcRanking', edgelist, likelihood, module_size, start, end)
}

probabilistic_rank_internal <- function(edgelist, df_nodes) {
    .Call('_mcmcRanking_probabilistic_rank_internal', PACKAGE = 'mcmcRanking', edgelist, df_nodes)
}

real_prob_internal <- function(edgelist, likelihood) {
    .Call('_mcmcRanking_real_prob_internal', PACKAGE = 'mcmcRanking', edgelist, likelihood)
}

#' Accurate sum of numbers
#'
#' Sums every time only two smallest numbers.
#' This allows calculate the sum of numbers accurate enough.
#' @export
accurate_sum <- function(v) {
    .Call('_mcmcRanking_accurate_sum', PACKAGE = 'mcmcRanking', v)
}

